 
services:
  app:
    volumes:
      - .:/var/www
      - /var/www/vendor 
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    command: sh -c "composer install && php artisan migrate && apache2-foreground"
